### ISSUE TITLE
Downloads no longer working

### ISSUE THREAD

**Issue by redfast00** [Mikescher/BefunExec#1]
Appveyor removes build artifacts after a year

**Comment by Mikescher** [comment]
Well .... TIL

I forced a re-run of the AppVeyor build so the artifact should be good for another year :).  
But I also added a [github release](https://github.com/Mikescher/BefunExec/releases/tag/2017-10-16) with the current version

**Comment by Mikescher** [comment]
Okay - all download links are updated (or all I could think of).

Thanks for the info - I guess I would never noticed myself
